kind: pipeline
type: docker
name: unit_test

steps:
  - name: test
    image: golang:1.19
    environment:
      MODE: test
    commands: 
      - go build -buildvcs=false .
      - go test -v ./...

  - name: notification
    image: appleboy/drone-telegram
    when:
      status:
        - failure
        - success
    settings:
      token:
        from_secret: Telegram_gggoingdown_CI_bot_token
      to:
        from_secret: Telegram_chat_id
      message: >
        {{#success build.status}}
          Repository: {{repo.name}}
          Branch: {{commit.branch}}
          Commit message:  {{commit.message}}
          Message: Test succeeded. Good job.
          Version: {{build.number}}
        {{else}}
          Repository: {{repo.name}}
          Branch: {{commit.branch}}
          Version: {{build.number}}
          Commit message:  {{commit.message}}
          Message: Test failed. Fix me please.
          Version: {{build.number}}
        {{/success}}


trigger:
  ref:
  - refs/heads/**


