version: '3'
services:
  app:
    image: fiber-cookiecutter:latest
    container_name: fiber-cookiecutter
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    env_file:
      - ./new.env
